### ISSUE TITLE
EVA Dual 5015 Part Fan MOD

### ISSUE THREAD

**Issue by SuperSniffles** [EVA-3D/contrib-extras#6]
## Part name
EVA Dual 5015 Part Fan MOD

## Compatible EVA version
2.0.0 --> 2.2.1
## Related EVA parts

Replaces:
back_corexy
top_bmg_mgn15
adds:
top_bmg_mgn15_2x5015_Mod
back_corexy_2x5015_Mod
Cable_Chain_Mount_2x_5015_BMG
Cable_Chain_Mount_2x_5015_Frame

## Necessary Hardware BOM
2x 5015 Blower Fan
some M3 Screws

## Description
This Dual 5015 Part Fan mod replaces the single 5015 Part Fan located on the backplate with 2 5015 Part Fans moved to the sides. The mod is intended to supply a higher cooling capacity than the standard setup.

## Onshape or STEP files
files are attached

## Print instructions
LH = 0.2
Nozzle = 0.4
Supports needed

## Contributor
Supersniffles. 

[5015.zip](https://github.com/EVA-3D/contrib-extras/files/6132507/5015.zip)

**Comment by miklschmidt** [comment]
Thank you!

Finally got around to add it (see EVA-3D/contrib-extras@85afc9e)!

Check it [here](https://contrib.eva-3d.page/cooling/dual_5015_part_fan/) and [here](https://contrib.eva-3d.page/cable_chain/dual_5015_part_fan_cable_chain/)
