### ISSUE TITLE
XY Cable Chain Mod

### ISSUE THREAD

**Issue by SuperSniffles** [EVA-3D/contrib-extras#9]
Part name
EVA Dual 5015 Part Fan MOD

Compatible EVA version
2.0.0 --> 2.2.1

Related EVA parts

Replaces:
none

adds:
XY_BMG_Mount (use this if you already use my 5015 dual fan mod)
XY_BMG_Mount_Std (use this for the original setup with one fan on the back)
XY_Chain_stepper_slider
XY_Back_ADXL_opt (optional if you want to use ADXL)
XY_Mount_clip-20
XY_Mount_clip-20_Hood

Necessary Hardware BOM
Cable Chain https://www.amazon.de/gp/product/B07VGC8QJR/ref=ppx_yo_dt_b_asin_title_o00_s00?ie=UTF8&psc=1
some M3 Screws
some M5 Screws
some drop in T-Nuts

Description
This Mod adds XY cable cain support to the V-Core. Nothing more to say.
[XY.zip](https://github.com/EVA-3D/contrib-extras/files/6207977/XY.zip)

Onshape or STEP files
files are attached

Print instructions
LH = 0.2
Nozzle = 0.4
Supports needed

Contributor
Supersniffles.

**Comment by miklschmidt** [comment]
Done.
